"""HTML report renderer."""

from __future__ import annotations

from pathlib import Path


def render_html(project_dir: Path) -> str:
    """Render an HTML test report.

    Parameters
    ----------
    project_dir:
        Root of the TestForge project.

    Returns
    -------
    str:
        HTML content.
    """
    name = project_dir.name
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TestForge Report: {name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; }}
        h1 {{ color: #1a1a2e; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #ddd; padding: 0.5rem 1rem; text-align: left; }}
        th {{ background: #f4f4f4; }}
        .passed {{ color: #28a745; }}
        .failed {{ color: #dc3545; }}
        footer {{ margin-top: 2rem; color: #666; font-size: 0.9rem; }}
    </style>
</head>
<body>
    <h1>TestForge Report: {name}</h1>
    <h2>Summary</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Total Tests</td><td>0</td></tr>
        <tr><td>Passed</td><td class="passed">0</td></tr>
        <tr><td>Failed</td><td class="failed">0</td></tr>
        <tr><td>Skipped</td><td>0</td></tr>
    </table>
    <h2>Test Results</h2>
    <p><em>No test results available.</em></p>
    <footer>Generated by <a href="https://github.com/songblaq/testforge">TestForge</a></footer>
</body>
</html>"""
