"""Markdown report renderer."""

from __future__ import annotations

from pathlib import Path


def render_markdown(project_dir: Path) -> str:
    """Render a Markdown test report.

    Parameters
    ----------
    project_dir:
        Root of the TestForge project.

    Returns
    -------
    str:
        Markdown content.
    """
    name = project_dir.name
    lines = [
        f"# TestForge Report: {name}",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        "| Total Tests | 0 |",
        "| Passed | 0 |",
        "| Failed | 0 |",
        "| Skipped | 0 |",
        "",
        "## Test Results",
        "",
        "_No test results available._",
        "",
        "---",
        "_Generated by [TestForge](https://github.com/songblaq/testforge)_",
    ]
    return "\n".join(lines)
