"""Markdown report renderer."""

from __future__ import annotations

import string
from datetime import datetime
from pathlib import Path

from testforge.report.generator import TestRun


# ---------------------------------------------------------------------------
# Jinja2 template (with string.Template fallback)
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# TestForge Report: {{ project }}

_Generated: {{ generated_at }}_

---

## Summary

| Metric | Value |
|--------|-------|
| Total  | {{ total }} |
| Passed | {{ passed }} |
| Failed | {{ failed }} |
| Skipped | {{ skipped }} |
{% if pass_rate is not none %}| Pass Rate | {{ pass_rate }}% |{% endif %}

{% if started_at or finished_at %}
## Execution Info

| Key | Value |
|-----|-------|
{% if started_at %}| Started | {{ started_at }} |{% endif %}
{% if finished_at %}| Finished | {{ finished_at }} |{% endif %}
{% for k, v in environment.items() %}| {{ k }} | {{ v }} |
{% endfor %}
{% endif %}

## Test Results

{% if results %}
{% for r in results %}
### {{ loop.index }}. {{ r.name }}

- **Status**: {{ status_badge(r.status) }}
- **ID**: `{{ r.id }}`
{% if r.duration_ms %}- **Duration**: {{ "%.0f"|format(r.duration_ms) }} ms{% endif %}
{% if r.tags %}- **Tags**: {{ r.tags | join(", ") }}{% endif %}
{% if r.steps %}

**Steps**:

{% for step in r.steps %}
{{ loop.index }}. {{ step.get("description", step.get("name", str(step))) }}{% if step.get("status") %} -- _{{ step["status"] }}_{% endif %}
{% endfor %}
{% endif %}
{% if r.error_message %}

**Error**:

```
{{ r.error_message }}
```
{% endif %}
{% if r.screenshot_paths %}

**Screenshots**:

{% for path in r.screenshot_paths %}
- `{{ path }}`
{% endfor %}
{% endif %}

---
{% endfor %}
{% else %}
_No test results available._
{% endif %}

{% if all_screenshots %}
## Evidence Gallery

{% for path in all_screenshots %}
- `{{ path }}`
{% endfor %}
{% endif %}

---
_Generated by [TestForge](https://github.com/songblaq/testforge)_
"""

_SIMPLE_TEMPLATE = """\
# TestForge Report: $project

_Generated: $generated_at

---

## Summary

| Metric | Value |
|--------|-------|
| Total | $total |
| Passed | $passed |
| Failed | $failed |
| Skipped | $skipped |

## Test Results

$results_section

---
_Generated by [TestForge](https://github.com/songblaq/testforge)_
"""


def _status_badge(status: str) -> str:
    badges = {
        "passed": "PASSED",
        "failed": "FAILED",
        "skipped": "SKIPPED",
    }
    return badges.get(status.lower(), status.upper())


def _render_with_jinja2(test_run: TestRun) -> str:
    """Render using Jinja2."""
    from jinja2 import Environment

    env = Environment(trim_blocks=True, lstrip_blocks=True)
    env.globals["status_badge"] = _status_badge

    tmpl = env.from_string(_TEMPLATE)

    pass_rate = None
    if test_run.total > 0:
        pass_rate = round(test_run.passed / test_run.total * 100, 1)

    all_screenshots: list[str] = []
    for r in test_run.results:
        all_screenshots.extend(r.screenshot_paths)

    return tmpl.render(
        project=test_run.project,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        total=test_run.total,
        passed=test_run.passed,
        failed=test_run.failed,
        skipped=test_run.skipped,
        pass_rate=pass_rate,
        started_at=test_run.started_at,
        finished_at=test_run.finished_at,
        environment=test_run.environment,
        results=test_run.results,
        all_screenshots=all_screenshots,
        none=None,
    )


def _render_simple(test_run: TestRun) -> str:
    """Render using string.Template (no Jinja2 required)."""
    lines: list[str] = []
    for i, r in enumerate(test_run.results, 1):
        lines.append(f"### {i}. {r.name}")
        lines.append(f"- **Status**: {_status_badge(r.status)}")
        lines.append(f"- **ID**: `{r.id}`")
        if r.duration_ms:
            lines.append(f"- **Duration**: {r.duration_ms:.0f} ms")
        if r.tags:
            lines.append(f"- **Tags**: {', '.join(r.tags)}")
        if r.error_message:
            lines.append("")
            lines.append("**Error**:")
            lines.append("")
            lines.append("```")
            lines.append(r.error_message)
            lines.append("```")
        if r.screenshot_paths:
            lines.append("")
            lines.append("**Screenshots**:")
            for path in r.screenshot_paths:
                lines.append(f"- `{path}`")
        lines.append("")
        lines.append("---")

    results_section = "\n".join(lines) if lines else "_No test results available._"

    tmpl = string.Template(_SIMPLE_TEMPLATE)
    return tmpl.substitute(
        project=test_run.project,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        total=test_run.total,
        passed=test_run.passed,
        failed=test_run.failed,
        skipped=test_run.skipped,
        results_section=results_section,
    )


def render_markdown(test_run: TestRun) -> str:
    """Render a Markdown test report.

    Parameters
    ----------
    test_run:
        Aggregated test run data.

    Returns
    -------
    str:
        Markdown content.
    """
    try:
        return _render_with_jinja2(test_run)
    except ImportError:
        return _render_simple(test_run)
